version: "3.3"

services:
  backend:
    build: ./backend
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4000"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports: 
      - "4000:4000"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=vhg_challenge
      - PORT=4000
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always